services:
  postgres:
    image: postgres:17
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - path: .env
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - dev-network

networks:
  dev-network:
    driver: bridge

volumes:
  pgdata:
