// AUTO-GENERATED by scripts/gen-default-maps.mjs — DO NOT EDIT BY HAND.
// Run `pnpm --filter @tau/front gen:default-maps` to regenerate.
// Source: apps/front/public (17 folders, 32 difficulties).

/** One built-in beatmap folder under /public and the .osu difficulties it ships. */
export type DefaultMapFolder = {
  /** Folder name under /public, e.g. "centimeter". */
  folder: string;
  /** .osu filenames within the folder, e.g. ["hard.osu", "normal.osu"]. */
  osuFiles: string[];
};

export const DEFAULT_MAP_FOLDERS: DefaultMapFolder[] = [
  {
    "folder": "asymmetry",
    "osuFiles": [
      "asymmetry.osu"
    ]
  },
  {
    "folder": "black_rover",
    "osuFiles": [
      "black_rover.osu"
    ]
  },
  {
    "folder": "centimeter",
    "osuFiles": [
      "hard.osu",
      "insane.osu",
      "normal.osu"
    ]
  },
  {
    "folder": "hanairo_biyori",
    "osuFiles": [
      "beginner.osu",
      "extra.osu"
    ]
  },
  {
    "folder": "holdin_on",
    "osuFiles": [
      "easy.osu",
      "extra.osu"
    ]
  },
  {
    "folder": "inferno",
    "osuFiles": [
      "inferno.osu",
      "inferno_normal.osu"
    ]
  },
  {
    "folder": "machinegun_poem_doll",
    "osuFiles": [
      "extra.osu",
      "hard.osu",
      "insane.osu"
    ]
  },
  {
    "folder": "make_a_move",
    "osuFiles": [
      "make_a_move.osu"
    ]
  },
  {
    "folder": "megalovania",
    "osuFiles": [
      "beginner.osu",
      "hard.osu",
      "insane.osu"
    ]
  },
  {
    "folder": "monster_effect",
    "osuFiles": [
      "monster_effect.osu"
    ]
  },
  {
    "folder": "no_title",
    "osuFiles": [
      "easy.osu",
      "expert.osu",
      "extra.osu",
      "hard.osu",
      "insane.osu"
    ]
  },
  {
    "folder": "nyan_pasu_bang_bang",
    "osuFiles": [
      "beginner.osu"
    ]
  },
  {
    "folder": "red_lips",
    "osuFiles": [
      "beginner.osu"
    ]
  },
  {
    "folder": "stronger_than_you",
    "osuFiles": [
      "beginner.osu"
    ]
  },
  {
    "folder": "symphony_of_the_night",
    "osuFiles": [
      "extra.osu"
    ]
  },
  {
    "folder": "through_the_fire_and_flames",
    "osuFiles": [
      "extra.osu"
    ]
  },
  {
    "folder": "tower_of_heaven",
    "osuFiles": [
      "another.osu",
      "hard.osu",
      "normal.osu"
    ]
  }
];
