// This file is auto-generated by @hey-api/openapi-ts
//
// ⚠️ DO NOT RUN `pnpm generate` / `turbo run generate` (back-schemas generate).
// The currently-installed @hey-api/openapi-ts emits a DIFFERENT, incompatible
// shape — split `zXxxQuery`/`zXxxPath`/`zXxxBody`/`zXxxResponse` exports instead
// of the combined `zXxxData` objects that `fetchBackend.ts` consumes via
// `.shape.query`. Regenerating wipes every `...Data` export and breaks all
// frontend routes at runtime. (Booting the backend dev server is fine — it only
// rewrites openapi.json; it does NOT run the generator.) This file is
// hand-maintained until the generator version is pinned back to the
// `...Data`-emitting release (see project memory: back-schemas-generator-drift).
// Add new routes/fields here by hand in this same `...Data` format.

import { z } from 'zod';

export const zGetOsuBeatmapsetsSearchResponseDtoOutput = z.object({
    beatmapsets: z.array(z.object({
        beatmaps: z.array(z.object({
            url: z.string(),
            mode: z.string(),
            mode_int: z.number(),
            difficulty_rating: z.number(),
            total_length: z.number(),
            version: z.string(),
            id: z.number()
        })),
        artist: z.string(),
        title: z.string(),
        creator: z.string(),
        id: z.number(),
        status: z.string(),
        covers: z.record(z.string(), z.string())
    }))
});

export const zGetOsuDailyResponseDtoOutput = z.object({
    date: z.string(),
    beatmapsetId: z.number(),
    title: z.string(),
    artist: z.string(),
    creator: z.string(),
    coverUrl: z.string(),
    lengthSeconds: z.number(),
    beatmapIds: z.array(z.number()),
    difficulties: z.array(z.object({
        id: z.number(),
        version: z.string(),
        stars: z.number()
    })),
    starRange: z.object({
        min: z.number(),
        max: z.number()
    }),
    degraded: z.boolean()
});

export const zGetScoresBeatmapLeaderboardResponseDtoOutput = z.object({
    leaderboard: z.array(z.object({
        playerName: z.string().min(1).max(32),
        beatmapId: z.string().min(1).max(32),
        score: z.int().gte(0).lte(9007199254740991),
        maxCombo: z.int().gte(0).lte(9007199254740991),
        accuracy: z.number().gte(0),
        missCount: z.int().gte(0).lte(9007199254740991),
        mehCount: z.int().gte(0).lte(9007199254740991),
        goodCount: z.int().gte(0).lte(9007199254740991),
        greatCount: z.int().gte(0).lte(9007199254740991),
        perfectCount: z.int().gte(0).lte(9007199254740991),
        submissionTime: z.iso.datetime().regex(/^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d(?::[0-5]\d(?:\.\d+)?)?(?:Z))$/),
        scoreVersion: z.int().gte(0).lte(9007199254740991),
        modded: z.boolean(),
        mods: z.string().max(64)
    }))
});

export const zGetScoresBeatmapPersonalBestResponseDtoOutput = z.object({
    playerName: z.string().min(1).max(32),
    beatmapId: z.string().min(1).max(32),
    score: z.int().gte(0).lte(9007199254740991),
    maxCombo: z.int().gte(0).lte(9007199254740991),
    accuracy: z.number().gte(0),
    missCount: z.int().gte(0).lte(9007199254740991),
    mehCount: z.int().gte(0).lte(9007199254740991),
    goodCount: z.int().gte(0).lte(9007199254740991),
    greatCount: z.int().gte(0).lte(9007199254740991),
    perfectCount: z.int().gte(0).lte(9007199254740991),
    submissionTime: z.iso.datetime().regex(/^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d(?::[0-5]\d(?:\.\d+)?)?(?:Z))$/),
    scoreVersion: z.int().gte(0).lte(9007199254740991),
    modded: z.boolean(),
    mods: z.string().max(64)
});

export const zPostScoresSubmitBodyDto = z.object({
    playerName: z.string().min(1).max(32),
    beatmapId: z.string().min(1).max(32),
    score: z.int().gte(0).lte(9007199254740991),
    maxCombo: z.int().gte(0).lte(9007199254740991),
    accuracy: z.number().gte(0),
    missCount: z.int().gte(0).lte(9007199254740991),
    mehCount: z.int().gte(0).lte(9007199254740991),
    goodCount: z.int().gte(0).lte(9007199254740991),
    perfectCount: z.int().gte(0).lte(9007199254740991),
    modded: z.boolean(),
    mods: z.string().max(64)
});

export const zPostScoresSubmitResponseDtoOutput = z.object({
    wasUploaded: z.boolean(),
    score: z.object({
        playerName: z.string().min(1).max(32),
        beatmapId: z.string().min(1).max(32),
        score: z.int().gte(0).lte(9007199254740991),
        maxCombo: z.int().gte(0).lte(9007199254740991),
        accuracy: z.number().gte(0),
        missCount: z.int().gte(0).lte(9007199254740991),
        mehCount: z.int().gte(0).lte(9007199254740991),
        goodCount: z.int().gte(0).lte(9007199254740991),
        greatCount: z.int().gte(0).lte(9007199254740991),
        perfectCount: z.int().gte(0).lte(9007199254740991),
        submissionTime: z.iso.datetime().regex(/^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d(?::[0-5]\d(?:\.\d+)?)?(?:Z))$/),
        scoreVersion: z.int().gte(0).lte(9007199254740991),
        modded: z.boolean(),
        mods: z.string().max(64)
    })
});

export const zOsuControllerBeatmapsetsSearchData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.object({
        q: z.optional(z.string().max(100)).default('')
    }))
});

export const zOsuControllerBeatmapsetsSearchResponse = zGetOsuBeatmapsetsSearchResponseDtoOutput;

export const zOsuControllerDailyData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.object({}))
});

export const zOsuControllerDailyResponse = zGetOsuDailyResponseDtoOutput;

export const zScoresControllerGetBeatmapLeaderboardData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        beatmapId: z.string().min(1).max(32)
    }),
    query: z.optional(z.object({
        scoreVersion: z.optional(z.number().gte(1).lte(3)).default(3),
        modded: z.optional(z.boolean()).default(false)
    }))
});

export const zScoresControllerGetBeatmapLeaderboardResponse = zGetScoresBeatmapLeaderboardResponseDtoOutput;

export const zScoresControllerGetBeatmapPersonalBestData = z.object({
    body: z.optional(z.never()),
    path: z.object({
        beatmapId: z.string().min(1).max(32),
        playerName: z.string().min(1).max(32)
    }),
    query: z.optional(z.object({
        scoreVersion: z.optional(z.number().gte(1).lte(3)).default(3),
        modded: z.optional(z.boolean()).default(false)
    }))
});

export const zScoresControllerGetBeatmapPersonalBestResponse = zGetScoresBeatmapPersonalBestResponseDtoOutput;

export const zScoresControllerSubmitScoreData = z.object({
    body: zPostScoresSubmitBodyDto,
    path: z.optional(z.never()),
    query: z.optional(z.never())
});

export const zScoresControllerSubmitScoreResponse = zPostScoresSubmitResponseDtoOutput;
