// This file is auto-generated by @hey-api/openapi-ts

import { z } from 'zod';

export const zBeatmapsetsSearchResponseDtoOutput = z.object({
    beatmapsets: z.array(z.object({
        beatmaps: z.array(z.object({
            url: z.string(),
            mode: z.string(),
            difficulty_rating: z.number(),
            id: z.number()
        })),
        artist: z.string(),
        title: z.string(),
        creator: z.string(),
        id: z.number(),
        covers: z.record(z.string(), z.string())
    }))
});

export const zOsuControllerBeatmapsetsSearchData = z.object({
    body: z.optional(z.never()),
    path: z.optional(z.never()),
    query: z.optional(z.object({
        q: z.optional(z.string().max(100)).default('')
    }))
});

export const zOsuControllerBeatmapsetsSearchResponse = zBeatmapsetsSearchResponseDtoOutput;
