import "./global.css";
import localFont from "next/font/local";

export const metadata = {
  title: "Welcome to ",
  description: "Generated by create-nx-workspace",
};

const rostex = localFont({
  src: [
    {
      path: "../../public/Rostex-Regular.ttf",
    },
  ],
  variable: "--font-rostex",
});

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
